[package]
org = "ballerina"
name = "sql"
version = "0.6.0-alpha5"

[[platform.java11.dependency]]
path = "../sql-native/build/libs/sql-native-0.6.0-alpha5-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "sql-native"
version = "0.6.0-alpha5-SNAPSHOT"

[[platform.java11.dependency]]
path = "../sql-test-utils/build/libs/sql-test-utils-0.6.0-alpha5-SNAPSHOT.jar"
groupId = "org.ballerinalang"
scope = "testOnly"
artifactId = "sql"
version = "0.6.0-alpha5-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/HikariCP-3.3.1.jar"
groupId = "com.zaxxer"
artifactId = "HikariCP"
version = "3.3.1"

[[platform.java11.dependency]]
path = "./lib/hsqldb-2.5.1.jar"
groupId = "org.hsqldb"
scope = "testOnly"
artifactId = "hsqldb"
version = "2.5.1"
